### ISSUE TITLE
AWS::ElasticLoadBalancingV2::TargetGroup not supported ?

### ISSUE THREAD

**Issue by ffoysal** [coreos/grafiti#128]
The resource type AWS::ElasticLoadBalancingV2::TargetGroup is not supported ?
config file looks like 
```
resourceTypes = ["AWS::ElasticLoadBalancingV2::TargetGroup"]
endHour = 0
startHour = -8
endTimeStamp = "2017-08-21T01:01:01Z"
startTimeStamp = "2017-06-20T01:01:01Z"
```
tag.json file look like
```
{
	"TagFilters": [
		{
			"Key": "Name",
			"Values": ["tf-ws-tg"]
		}
	]
}
```
and the output
```
grafiti  delete -f example-tags-input.json
{"level":"info","msg":"Using config file: /home/foysal/.grafiti.toml","time":"2017-08-21T16:10:45-04:00"}
{"level":"info","msg":"using log level 'info'","time":"2017-08-21T16:10:45-04:00"}
{"level":"info","msg":"logging to stderr","time":"2017-08-21T16:10:45-04:00"}
Error: delete: rgta: get resources: InvalidParameterException: Unsupported ResourceType - 
	status code: 400, request id: d0e07fa3-86ac-11e7-af7d-3f11a27350d4
```

Help is very much appreciated

**Comment by estroz** [comment]
The [resource group tagging API](http://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/Welcome.html) does not support `AWS::ElasticLoadBalancingV2::TargetGroup` resources, according to the error message returned. Furthermore, grafiti only supports [classic load balancers](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb.html) as of now. You won't be able to delete TargetGroups using grafiti until TargetGroup-specific API calls are implemented, and this feature is not on the [roadmap](https://github.com/coreos/grafiti/blob/master/roadmap.md).
