### ISSUE TITLE
Add a note that tags are case sensitive

### ISSUE THREAD

**Issue by brianredbeard** [coreos/grafiti#93]
Currently at CoreOS we standardized on the format createdBy (established
during the initial scoping of grafiti and published internally to the 
engineering team).  If users were to pedantically follow the directions in this
repo, or look to the repo to figure out what tags they should be using, they
have the potential of resources being deleted when there is a condition where
grafiti does not handle a resource type.

**Comment by estroz** [comment]
I'll add a note in the filter and delete doc sections about tag sensitivity.

Can you elaborate on your last sentence? Resources cannot be deleted if grafiti does not implement a deleter for that resource type.
